server:
  port: 7538

spring:
  application:
    name: service-1
  profiles:
    active: mysql
    #set the static content locations eg. js/css/html
  resources:
    static-locations: classpath:/static
  freemarker:
    template-loader-path: classpath:/templates
  servlet:
    multipart:
      max-file-size: 100MB
  zipkin:
    base-url: http://207.148.77.180:9411
    sleuth:
      sampler:
        percentage: 1.0


feign:
  hystrix:
    enabled: true
jjwt:
  signatureKey: lEKiw5VnN2Rf3rV4NZxtsrl70ogHX2piwE0Ecj+NNiwsPG9kdmqwxHBCa839g5M91jm8JDs2b4FfhF/iRTPvYQ==
  issuer: http://localhost:7537

sftp:
  host: 45.32.253.252
  port: 22
  userName: root
  password: 272232

eureka:
  instance:
    hostname: localhost
    status-page-url: http://${eureka.instance.hostname}:${server.port}/swagger-ui.html
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 10
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true

mybatis:
  mapper-locations: classpath:com/example/service1/mapper/**/*.xml

logging:
  level:
    com.example: debug
  file:  ./files/${spring.application.name}.log

---

spring:
  profiles: oracle
  datasource:
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:oracle:thin:@//localhost:1521/ORCL
    username: SYSTEM
    password: 272232
    tomcat:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      test-on-borrow: true
      test-while-idle: false
      validation-query: SELECT 1 from dual

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7537/eureka/

---

spring:
  profiles: mysql
  datasource:
#    url: jdbc:mysql://localhost:3306/biefeng
    url: jdbc:mysql://10.128.62.33:3306/jy_catering?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&tinyInt1isBit=false
    username: root
    password: root
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      driver-class-name:
        com.mysql.jdbc.Driver

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7537/eureka/
